# Generated by Django 6.0.3 on 2026-04-28 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Registado', 'Registado'), ('Subscritor', 'Subscritor'), ('Editor', 'Editor'), ('Admin', 'Admin')], default='Registado', max_length=20)),
                ('estado', models.CharField(choices=[('Por_Ativar', 'Por Ativar'), ('Ativada', 'Ativada'), ('Bloqueada', 'Bloqueada'), ('Eliminado', 'Eliminado')], default='Por_Ativar', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Reportada', 'Reportada'), ('Apagada', 'Apagada')], default='Normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('corpo_texto', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('estado_publicacao', models.CharField(choices=[('pre_ai', 'Pré-AI'), ('pendente', 'Pendente'), ('publicada', 'Publicada')], default='pendente', max_length=20)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('acesso', models.CharField(choices=[('publico', 'Público'), ('premium', 'Premium')], max_length=20)),
                ('categoria_1', models.CharField(blank=True, choices=[('politica', 'Política'), ('economia', 'Economia'), ('tecnologia', 'Tecnologia'), ('ciencia', 'Ciência'), ('educacao', 'Educação'), ('internacional', 'Internacional'), ('nacional', 'Nacional'), ('desporto', 'Desporto'), ('cultura', 'Cultura'), ('maritimo', 'Marítimo')], max_length=20, null=True)),
                ('categoria_2', models.CharField(blank=True, choices=[('politica', 'Política'), ('economia', 'Economia'), ('tecnologia', 'Tecnologia'), ('ciencia', 'Ciência'), ('educacao', 'Educação'), ('internacional', 'Internacional'), ('nacional', 'Nacional'), ('desporto', 'Desporto'), ('cultura', 'Cultura'), ('maritimo', 'Marítimo')], max_length=20, null=True)),
                ('categoria_3', models.CharField(blank=True, choices=[('politica', 'Política'), ('economia', 'Economia'), ('tecnologia', 'Tecnologia'), ('ciencia', 'Ciência'), ('educacao', 'Educação'), ('internacional', 'Internacional'), ('nacional', 'Nacional'), ('desporto', 'Desporto'), ('cultura', 'Cultura'), ('maritimo', 'Marítimo')], max_length=20, null=True)),
                ('origem_noticia', models.CharField(blank=True, choices=[('noticias_do_povo', 'Notícias do Povo')], max_length=20, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_escritas', to=settings.AUTH_USER_MODEL)),
                ('editor_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_aprovadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='com_soc.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Reportada', 'Reportada'), ('Apagada', 'Apagada')], default='Normal', max_length=20)),
                ('data_post', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='com_soc.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Apagada', 'Apagada')], default='Normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('estado', models.CharField(choices=[('Ativa', 'Ativa'), ('Expirada', 'Expirada'), ('Sem_Subscricao', 'Sem Subscrição')], default='Sem_Subscricao', max_length=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscricoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
